//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHospitalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int id { get; set; }
        public string pname { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string disease { get; set; }
        public Nullable<int> doctor { get; set; }
    
        public virtual Doctor Doctor1 { get; set; }
    }
}
